import { initializeApp, getApps, getApp, type FirebaseApp, type FirebaseOptions } from 'firebase/app';
import { getAuth, type Auth } from 'firebase/auth';
import { getFirestore, type Firestore } from 'firebase/firestore';
import { getStorage, type FirebaseStorage } from 'firebase/storage';
import { getFunctions, type Functions } from 'firebase/functions';
import { describeFirebaseConfigSource, readFirebaseConfigFromEnv } from './env-config';

export interface CaspianFirebase {
  app: FirebaseApp;
  auth: Auth;
  db: Firestore;
  storage: FirebaseStorage;
  functions: Functions;
}

export interface InitFirebaseOptions {
  config: FirebaseOptions;
  /** Optional instance name — useful when mounting multiple shops on one page. */
  name?: string;
  /** Optional region for Cloud Functions (default: us-central1). */
  functionsRegion?: string;
}

export function initCaspianFirebase({
  config: passedConfig,
  name,
  functionsRegion = 'us-central1',
}: InitFirebaseOptions): CaspianFirebase {
  const instanceName = name ?? 'caspian-store';
  // Auto-heal: fill any missing fields from FIREBASE_WEBAPP_CONFIG (Firebase
  // App Hosting auto-injects it) or NEXT_PUBLIC_FIREBASE_* (Vercel / local).
  // Lets consumers whose `caspianFirebaseConfig` was generated by older
  // scaffolders (the inline `process.env.NEXT_PUBLIC_FIREBASE_*!` literal
  // resolves to undefined when those vars aren't set) still deploy to App
  // Hosting without modifying their adapter file. Passed values always win,
  // so explicit overrides keep working.
  const envConfig = readFirebaseConfigFromEnv();
  const config: FirebaseOptions = {
    apiKey: passedConfig.apiKey || envConfig.apiKey,
    authDomain: passedConfig.authDomain || envConfig.authDomain,
    projectId: passedConfig.projectId || envConfig.projectId,
    storageBucket: passedConfig.storageBucket || envConfig.storageBucket,
    messagingSenderId: passedConfig.messagingSenderId || envConfig.messagingSenderId,
    appId: passedConfig.appId || envConfig.appId,
  };
  // Pre-check the four required fields before handing off to Firebase. The
  // SDK's own error (`auth/invalid-api-key`) surfaces during a Next.js
  // /_not-found prerender as an opaque crash that doesn't tell the consumer
  // which env source to fix; this guard names the missing field(s) and the
  // detected platform. storageBucket and messagingSenderId are intentionally
  // not required — some Firebase products work without them.
  const missing = (['apiKey', 'authDomain', 'projectId', 'appId'] as const).filter(
    (k) => !config[k],
  );
  if (missing.length) {
    throw new Error(
      `Caspian Store: Firebase config is missing required field(s): ${missing.join(', ')}. ` +
        `Auto-heal could not find them in FIREBASE_WEBAPP_CONFIG (Firebase Console-created App Hosting backends auto-inject this at BUILD time) ` +
        `or in NEXT_PUBLIC_FIREBASE_* (Vercel / .env.local). ` +
        `Detected platform: ${describeFirebaseConfigSource()}. ` +
        `Fix: set the missing values in Firebase Console → App Hosting → backend → Environment, or in .env.local for local dev.`,
    );
  }
  const existing = getApps().find((a) => a.name === instanceName);
  const app = existing ?? initializeApp(config, instanceName);
  return {
    app,
    auth: getAuth(app),
    db: getFirestore(app),
    storage: getStorage(app),
    functions: getFunctions(app, functionsRegion),
  };
}

/**
 * Initialise Firebase if there is a usable config, otherwise return `null`.
 *
 * The throwing `initCaspianFirebase` above stays the default because a
 * storefront that silently comes up without Firebase is a storefront that fails
 * later and more confusingly. This variant exists for the one case where "no
 * Firebase project" is a legitimate configuration rather than a mistake: a
 * standalone till, which keeps its catalogue and sales on its own disk and has
 * no project to point at.
 */
export function tryInitCaspianFirebase(options: InitFirebaseOptions): CaspianFirebase | null {
  try {
    return initCaspianFirebase(options);
  } catch {
    return null;
  }
}

/** Fall back to the default Firebase app if the consumer has already initialized it. */
export function getDefaultCaspianFirebase(functionsRegion = 'us-central1'): CaspianFirebase | null {
  if (getApps().length === 0) return null;
  const app = getApp();
  return {
    app,
    auth: getAuth(app),
    db: getFirestore(app),
    storage: getStorage(app),
    functions: getFunctions(app, functionsRegion),
  };
}
