'use client';

import { createContext, useContext, useEffect, useState, type ReactNode } from 'react';
import type { SiteSettings } from '../types';
import { useCaspianFirebase, useCaspianNavigation } from '../provider/caspian-store-provider';
import { useTemplateComponent } from '../provider/template-provider';
import { useAuth } from '../context/auth-context';
import { getSiteSettings } from '../services/site-settings-service';
import type { SiteHeaderProps } from './site-header';
import type { SiteFooterProps } from './site-footer';
import { ComingSoonSplash } from './coming-soon-splash';
import { LayoutShellChromeDefault } from './variants/layout-shell-chrome-default';

// v7.2.0 self-heal sentinel. CaspianRoot owns the shell for every storefront
// path, but some consumer root layouts — notably `src/app/layout.tsx`
// generated by the v7.0.0 / v7.0.1 scaffolder — also wrap `{children}` in
// <LayoutShell>. When that happens the inner mount reads this context as
// `true` and renders just `{children}`, so header + footer stay single
// regardless of how many LayoutShells are in the tree. Upgrading the library
// is the complete fix — no consumer file edits required.
const LayoutShellMountedContext = createContext(false);

export interface LayoutShellProps {
  children: ReactNode;
  /** Path prefixes that should bypass the header + footer chrome (e.g. admin / auth flows). Default: `['/admin']`. */
  bypassPrefixes?: string[];
  /** Pass-through to <SiteHeader>. Set to `null` to disable. */
  header?: SiteHeaderProps | null;
  /** Pass-through to <SiteFooter>. Set to `null` to disable. */
  footer?: SiteFooterProps | null;
  /**
   * Vertical padding (px) inserted between the header / footer and the page
   * content. Defaults to 100. Set to 0 for full-bleed pages whose own first
   * block should sit flush against the header (e.g. the homepage hero).
   * Added in v8.11.
   */
  contentPaddingY?: number;
  /** Override pathname detection (mostly for tests). Defaults to the navigation adapter. */
  pathname?: string;
  /**
   * Query-string key used to bypass Coming Soon mode for a preview session
   * (e.g. `?caspian-preview=1`). When `SiteSettings.comingSoon.allowAdminPreview`
   * is false, the key is ignored. Default: `caspian-preview`. Added in v2.7.
   */
  previewQueryKey?: string;
}

const PREVIEW_STORAGE_KEY = 'caspian:coming-soon-preview';

/**
 * Wraps children in <SiteHeader> + <SiteFooter>, except on routes whose pathname
 * begins with one of `bypassPrefixes` (default `/admin`). Locale prefixes
 * (`/en`, `/ar`, etc.) are stripped before the prefix match so a path like
 * `/en/admin/products` is correctly recognized as an admin route.
 *
 * When `SiteSettings.comingSoon.enabled` is true and the visitor is not on a
 * bypass route or preview session, the children are replaced by a branded
 * splash (`<ComingSoonSplash>`). Signed-in admins also bypass the splash when
 * `SiteSettings.comingSoon.allowAdminPreview` is true (the default). Added in
 * v2.7; admin auto-bypass fixed in v4.0.1.
 */
export function LayoutShell({
  children,
  bypassPrefixes = ['/admin'],
  header,
  footer,
  contentPaddingY = 100,
  pathname: pathnameOverride,
  previewQueryKey = 'caspian-preview',
}: LayoutShellProps) {
  const alreadyMounted = useContext(LayoutShellMountedContext);
  const { db } = useCaspianFirebase();
  const nav = useCaspianNavigation();
  const { userProfile } = useAuth();
  const pathname = pathnameOverride ?? nav.pathname;
  const stripped = stripLocalePrefix(pathname);
  const bypass = bypassPrefixes.some((p) => stripped.startsWith(p));

  const [settings, setSettings] = useState<SiteSettings | null>(null);

  useEffect(() => {
    if (bypass || alreadyMounted) return undefined;
    let alive = true;
    getSiteSettings(db)
      .then((s) => {
        if (alive) setSettings(s);
      })
      .catch((err) => {
        console.warn('[caspian-store] LayoutShell site-settings fetch failed:', err);
        if (alive) setSettings(null);
      });
    return () => {
      alive = false;
    };
  }, [db, bypass, alreadyMounted]);

  // The active template's chrome variant. v9.0.0 reserved the `LayoutShell`
  // slot; v9.1.0 actually wires it. Variants only get to choose how the
  // chrome is composed — bypass routing, the coming-soon splash, and the
  // double-mount sentinel above are framework-level concerns held in this
  // dispatcher so each template doesn't have to re-implement them.
  // Hooks must always run, so resolve before the bypass branches return.
  const ChromeComponent = useTemplateComponent('LayoutShell', LayoutShellChromeDefault);

  if (alreadyMounted) return <>{children}</>;
  if (bypass) return <>{children}</>;

  const allowAdminPreview = settings?.comingSoon?.allowAdminPreview !== false;
  const isAdminPreview = allowAdminPreview && userProfile?.role === 'admin';

  if (
    settings?.comingSoon?.enabled &&
    !isAdminPreview &&
    !isPreviewSession(previewQueryKey, settings)
  ) {
    return <ComingSoonSplash settings={settings} />;
  }

  return (
    <LayoutShellMountedContext.Provider value={true}>
      <ChromeComponent header={header ?? null} footer={footer ?? null} contentPaddingY={contentPaddingY}>
        {children}
      </ChromeComponent>
    </LayoutShellMountedContext.Provider>
  );
}

/**
 * A preview session is granted when the page was loaded with
 * `?caspian-preview=1` (or the configured key) — we persist the flag to
 * sessionStorage so subsequent navigations inside the SPA keep the bypass.
 * When `allowAdminPreview` is false, the key is ignored.
 */
function isPreviewSession(queryKey: string, settings: SiteSettings): boolean {
  if (settings.comingSoon?.allowAdminPreview === false) return false;
  if (typeof window === 'undefined') return false;
  try {
    const url = new URL(window.location.href);
    if (url.searchParams.get(queryKey)) {
      window.sessionStorage.setItem(PREVIEW_STORAGE_KEY, '1');
      return true;
    }
    return window.sessionStorage.getItem(PREVIEW_STORAGE_KEY) === '1';
  } catch {
    return false;
  }
}

function stripLocalePrefix(pathname: string): string {
  const match = pathname.match(/^\/([a-z]{2})(\/|$)/i);
  if (!match) return pathname;
  return pathname.slice(match[1].length + 1) || '/';
}
