import type { Timestamp } from 'firebase/firestore';
import type { ShippingPluginId } from './shipping/types';

// --- Core e-commerce types ---

export interface ProductImage {
  id: string;
  url: string;
  alt: string;
  hint: string;
}

export interface ColorVariant {
  name: string;
  imageUrl: string;
}

export interface Product {
  id: string;
  /**
   * URL-safe slug derived from `name`, used for SEO-friendly product URLs
   * (`/product/black-leather-jacket` instead of `/product/abc123XYZ`). Optional
   * because pre-v8.3 documents have no `slug` field — the route handler falls
   * back to lookup by document id when this is missing, so legacy URLs keep
   * working. New products generated by `createProduct` always get one;
   * `updateProduct` lazily backfills missing slugs on the next save.
   */
  slug?: string;
  name: string;
  brand: string;
  /** Optional stock-keeping unit. Admin-entered free text; not enforced unique. */
  sku?: string;
  description: string;
  /**
   * Short marketing blurb shown in the PDP hero column above the Add-to-Cart
   * button. Kept separate from `description` so the storefront can show a
   * punchy 2–3 line pitch in the hero and the longer `description` in the
   * Details tab. Optional — falls back to the first ~240 chars of
   * `description` when empty.
   */
  shortDescription?: string;
  /**
   * Rich-text specs / dimensions rendered under the "Details" tab on the PDP.
   * Stored as sanitized HTML (allowlist: `<p>`, `<strong>`, `<ul>`, `<li>`,
   * `<br>`). Authored with the `<RichTextEditor>` in the admin product editor.
   * Optional — tab is hidden when empty and no `description` exists.
   */
  details?: string;
  price: number;
  images: ProductImage[];
  category: string;
  isNew?: boolean;
  limited?: boolean;
  sizes?: string[];
  color?: string;
  colorVariants?: ColorVariant[];
  stock?: Record<string, number>;
  /**
   * Enabled-taxonomy assignments: taxonomy id (`colors`, `materials`, `seasons`,
   * …) → array of `taxonomyTerms` doc ids. Populated by the product editor's
   * Attributes section from the common-taxonomies catalog; only generic
   * taxonomies land here (Brand keeps its own `brand` field, Sizes its own
   * `sizes`). Term ids are stable; display names resolve via `useTaxonomyTerms`.
   */
  taxonomies?: Record<string, string[]>;
  isActive?: boolean;
  /** Net weight in kilograms. Consumed by the Weight-Based shipping plugin; leave undefined if you don't use weight-based shipping. */
  weightKg?: number;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
}

export interface CartItemRef {
  productId: string;
  quantity: number;
  selectedSize?: string;
  selectedColor?: string;
}

/** Cart item = a cart line hydrated with its Product snapshot. */
export interface CartItem {
  product: Product;
  quantity: number;
  selectedSize?: string;
  selectedColor?: string;
}

export interface FirestoreCart {
  items: CartItemRef[];
  updatedAt: Timestamp;
}

export interface OrderItem {
  productId: string;
  name: string;
  brand: string;
  price: number;
  quantity: number;
  selectedSize: string | null;
  selectedColor: string | null;
  imageUrl: string;
}

export interface OrderPayment {
  stripeSessionId: string;
  last4: string;
  brand: string;
  amount: number;
  /**
   * Payment method identifier. Stripe orders omit this (current default) or
   * set `'stripe'`; manual-payment orders (BACS / cheque / cash on delivery)
   * set it to the matching plugin id so admins can filter + display the
   * right "awaiting payment" instructions. Added in v2.8.
   */
  method?: 'stripe' | 'bacs' | 'cheque' | 'cod';
}

export interface ShippingInfo {
  name: string;
  address: string;
  city: string;
  zip: string;
  country: string;
  shippingMethod: string;
  orderNotes?: string;
}

export interface Order {
  id: string;
  userId: string;
  userEmail: string;
  status: OrderStatus;
  items: OrderItem[];
  shippingInfo: ShippingInfo;
  payment: OrderPayment;
  subtotal: number;
  shippingCost: number;
  discount: number;
  promoCode: string | null;
  /**
   * Tax amount on the order, in the same currency as `total`. Optional for
   * backward compat — orders created before v2.12 won't have this field.
   * When present, `total = subtotal + shippingCost + tax - discount`.
   * Added in v2.12.
   */
  tax?: number;
  total: number;
  /**
   * True when the order was placed by an anonymous (Firebase anonymous-auth)
   * user — i.e. a WooCommerce-style guest checkout. `userId` still references
   * the anonymous account so Firestore rules continue to allow the buyer to
   * read their own order. The auth-trigger account-linking Cloud Function
   * re-stamps `userId` (and clears this flag) when a real account is later
   * created with the matching `userEmail`. Added in v9.1.
   */
  isGuest?: boolean;
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

export interface UserAddress {
  id: string;
  name: string;
  address: string;
  city: string;
  zip: string;
  country: string;
  isDefault: boolean;
}

export interface UserProfile {
  uid: string;
  email: string;
  displayName: string;
  photoURL: string | null;
  phone?: string;
  role: 'customer' | 'admin';
  addresses: UserAddress[];
  wishlist: string[];
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

export type OrderStatus =
  | 'pending'
  | 'paid'
  | 'processing'
  | 'shipped'
  | 'delivered'
  | 'cancelled'
  /**
   * Order is awaiting manual payment confirmation (bank transfer, cheque, COD).
   * The shopper has checked out but payment has not yet cleared; the admin
   * marks the order `paid` (or `cancelled`) once the funds arrive. Added in v2.8.
   */
  | 'on-hold';

export type ModerationStatus = 'pending' | 'approved' | 'rejected';

export interface FirestoreReview {
  id: string;
  productId: string;
  userId: string;
  author: string;
  photoURL: string | null;
  rating: number;
  text: string;
  createdAt: Timestamp;
  isVerifiedPurchase: boolean;
  status: ModerationStatus;
}

export interface FirestoreQuestion {
  id: string;
  productId: string;
  userId: string;
  author: string;
  photoURL: string | null;
  text: string;
  createdAt: Timestamp;
  answer: string | null;
  answeredAt: Timestamp | null;
  answeredByUid: string | null;
  status: ModerationStatus;
}

/**
 * CRM-style inbox state for a contact-page submission. Contacts are never
 * shown publicly, so the triad is `new | read | archived` rather than the
 * moderation triad used by reviews/questions. Added in v2.13.
 */
export type ContactStatus = 'new' | 'read' | 'archived';

/**
 * A single "Contact us" form submission, created by any visitor (auth not
 * required). Admin-only read/update/delete. Drives the admin notifications
 * bell (`status == 'new'` count) and the dashboard's Recent contacts card.
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  subject?: string;
  message: string;
  status: ContactStatus;
  createdAt: Timestamp;
  readAt?: Timestamp;
  /** Present only if the submitter happened to be signed in at submit time. */
  userId?: string;
}

// --- Admin-managed content types (v1.1+) ---

export interface FaqItem {
  id: string;
  category: string;
  question: string;
  answer: string;
  order: number;
}

export interface JournalArticle {
  id: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  imageUrl: string;
  content: string;
  createdAt: Timestamp;
}

export interface Subscriber {
  id: string;
  email: string;
  subscribedAt: Timestamp;
}

/**
 * Closed list of social-link platforms. Each value maps 1:1 to an icon in
 * `<SocialIcon>` — keep this in sync with `src/components/social-icon.tsx`.
 */
export type SocialPlatform =
  | 'instagram'
  | 'facebook'
  | 'twitter'
  | 'x'
  | 'youtube'
  | 'tiktok'
  | 'linkedin'
  | 'pinterest';

export const SOCIAL_PLATFORMS: readonly SocialPlatform[] = [
  'instagram',
  'facebook',
  'twitter',
  'x',
  'youtube',
  'tiktok',
  'linkedin',
  'pinterest',
] as const;

export interface SocialLink {
  platform: SocialPlatform;
  url: string;
}

/**
 * How tax is computed and rendered on the checkout page. See
 * `SiteSettings.taxMode` / `supportedCountries`.
 * - `flat`: every order uses the single `flatTaxRate`.
 * - `per-country`: per-entry `taxRate` on each row in `supportedCountries`;
 *   checkout reads the rate of the shopper's selected country.
 * - `none`: no tax row rendered anywhere.
 */
export type TaxMode = 'flat' | 'per-country' | 'none';

/**
 * Display + calculation preferences layered on top of the existing
 * `taxMode` / `flatTaxRate` / per-country rate surface. None of these are
 * required — defaults preserve pre-v2.12 behavior. Added in v2.12.
 *
 * Full WooCommerce-parity tax classes and multi-rate tables are intentionally
 * out of scope for v2.x — they would require a parallel collection schema
 * that conflicts with the existing `SiteSettings.supportedCountries[].taxRate`
 * field. Revisit as a v3 breaking change.
 */
export interface TaxConfig {
  /**
   * When `true`, prices entered by the merchant in the product editor are
   * treated as *including* tax — the storefront strips it out on the fly.
   * When `false` (default, pre-v2.12 behavior), prices are tax-exclusive.
   */
  pricesEnteredWithTax: boolean;
  /**
   * Which address drives the rate lookup under `taxMode: 'per-country'`.
   * - `shipping` (default): use the shopper's shipping-address country.
   * - `billing`: use the shopper's billing-address country (reserved — checkout
   *   doesn't collect a separate billing address yet; falls back to shipping).
   * - `store`: use `SiteSettings.country` regardless of where the shopper is.
   */
  taxBasedOn: 'shipping' | 'billing' | 'store';
  /**
   * When `true`, tax is computed once on the subtotal and rounded; when
   * `false`, tax is computed per line and each line rounded before summing.
   * Only matters once per-line tax is implemented (stored as
   * `OrderItem.taxAmount`); today's single-rate engine is unaffected.
   */
  roundAtSubtotalLevel: boolean;
  /** Whether PLP/PDP prices render tax-inclusive (`incl`) or tax-exclusive (`excl`). Default `excl`. */
  displayPricesInShop: 'incl' | 'excl';
  /** Same, for the cart and checkout pages. Default `excl`. */
  displayPricesCartCheckout: 'incl' | 'excl';
  /**
   * Suffix appended after every rendered price (e.g. `"incl. VAT"`, `"ex. GST"`).
   * Empty string to suppress. Supports the `{rate}` placeholder — resolved to
   * the active decimal rate (e.g. `0.08` → `"8%"`).
   */
  priceDisplaySuffix: string;
  /**
   * How tax totals render on the checkout summary.
   * - `single`: one "Tax: $X" row (default, matches pre-v2.12 behavior).
   * - `itemized`: one row per tax class — reserved for v3 multi-class work;
   *   with today's single-rate engine this renders the same as `single`.
   */
  displayTaxTotals: 'single' | 'itemized';
}

/**
 * A country the store sells to. Populates the country dropdown in checkout —
 * shoppers can only pick from this list. Under `taxMode: 'per-country'`, the
 * `taxRate` field is also consumed.
 */
export interface SupportedCountry {
  /** ISO 3166-1 alpha-2 code, uppercase (e.g. `US`, `GB`). */
  code: string;
  /** Display name used in the checkout country dropdown (e.g. `United States`). */
  name: string;
  /** Decimal tax rate 0–1 (e.g. `0.08` for 8%). Only used under per-country mode. */
  taxRate?: number;
}

/**
 * Coming Soon / Maintenance mode config. When `enabled: true`, the storefront
 * short-circuits to a branded splash for non-admin visitors. Admin routes and
 * (optionally) admin-authenticated viewers continue to see the real site.
 * Added in v2.7.
 */
export interface ComingSoonSettings {
  enabled: boolean;
  /** Optional override of the splash body copy. Defaults to "We're launching soon." */
  message?: string;
  /** When true, admin-authenticated viewers bypass the splash and see the real site. Default true. */
  allowAdminPreview: boolean;
}

/**
 * How prices render across the storefront (symbol position, separators,
 * decimals). Consumed by `formatCurrency`. When omitted, the library falls
 * back to `Intl.NumberFormat` defaults for the active locale. Added in v2.7.
 */
export interface CurrencyDisplay {
  /** Where the currency symbol sits relative to the number. */
  position: 'left' | 'right' | 'left_space' | 'right_space';
  /** Thousands separator. Typical values: `,`, `.`, ` `, `'`. */
  thousandSep: string;
  /** Decimal separator. Typical values: `.`, `,`. */
  decimalSep: string;
  /** Number of decimal places. Set to 0 for zero-decimal currencies (JPY, KRW). */
  decimals: number;
}

/**
 * Structured store address (WooCommerce-style). Replaces the single free-text
 * `contactAddress` field — that one stays for backward compat and is
 * best-effort-migrated into `line1` when this object is absent. Added in v2.7.
 */
export interface StoreAddress {
  line1: string;
  line2?: string;
  city: string;
  /** State / region / province / county — freeform if the country has no subdivisions. */
  stateOrRegion: string;
  /** ISO 3166-1 alpha-2 country code (e.g. `US`, `GB`). */
  country: string;
  postcode: string;
}

/** Days of the week, keyed for the structured business-hours schedule. */
export type Weekday = 'mon' | 'tue' | 'wed' | 'thu' | 'fri' | 'sat' | 'sun';

/** Open/close window for a single weekday. Times are `'HH:MM'` (24h). */
export interface BusinessDayHours {
  /** Whether the store is open this day. When `false`, `from`/`to` are ignored. */
  open: boolean;
  from: string;
  to: string;
}

/**
 * Structured weekly opening hours. When `enabled`, the storefront renders it
 * (currently on `/contact`); otherwise nothing shows. Supersedes the free-text
 * `SiteSettings.businessHours`, which is kept for backward compatibility.
 * `timezone` is a required string (default `''`) so the object never carries a
 * nested `undefined` — the settings save only strips *top-level* undefined and
 * Firestore rejects nested ones.
 */
export interface BusinessHoursSchedule {
  enabled: boolean;
  timezone: string;
  days: Record<Weekday, BusinessDayHours>;
}

/**
 * Review-submission policy toggles. Enforced by the `createReview` service;
 * `showVerifiedBadge` is read by the review card. Added in v2.7.
 */
export interface ReviewPolicy {
  /** When true, non-verified buyers are rejected at `createReview`. */
  restrictToVerifiedBuyers: boolean;
  /** When true, `createReview` rejects submissions without a star rating. */
  requireStarRating: boolean;
  /** When false, the "verified purchase" badge is hidden even on verified reviews. Default true. */
  showVerifiedBadge: boolean;
}

/**
 * Cart / add-to-cart behavior toggles read by PLP and PDP handlers. Added in v2.7.
 */
export interface CartBehavior {
  /** When true, clicking add-to-cart navigates the shopper to `/cart`. Default false. */
  redirectToCartAfterAdd: boolean;
  /** Reserved for future: async add-to-cart from product list pages without a full-page round trip. */
  ajaxOnArchives: boolean;
}

/**
 * Global inventory settings consumed by storefront badging, PLP filtering,
 * and the per-product stock fields in the admin product editor. Per-size
 * stock counts live on `Product.stock`. Added in v2.9.
 */
export interface InventorySettings {
  /** Master toggle. When false, all of the toggles below are inert and stock is not displayed. */
  trackStock: boolean;
  /** Total units across all sizes at or below this number trigger the "low stock" badge. */
  lowStockThreshold: number;
  /** Per-size unit count at or below this number is considered out of stock. Defaults to 0. */
  outOfStockThreshold: number;
  /**
   * Catalog visibility for products that are entirely out of stock (every size at or below
   * `outOfStockThreshold`). `'show'` keeps them visible (with badge); `'hide'` filters them
   * out of `getProducts` results.
   */
  outOfStockVisibility: 'show' | 'hide';
  /**
   * When badges render. `'always'` shows in-stock count on every card; `'low'` only shows
   * a badge when stock is at or below `lowStockThreshold`; `'never'` suppresses badges.
   */
  stockDisplay: 'always' | 'low' | 'never';
}

/**
 * Global shipping checkout-behavior toggles consumed by `<CheckoutPage>` when
 * computing which rates to render. Added in v2.9.
 */
export interface ShippingOptions {
  /**
   * When true, the checkout shipping picker stays empty until the shopper
   * has entered a country *and* a postal code. Useful when zone-derived
   * rates would otherwise mislead the customer pre-address.
   */
  hideRatesUntilAddressEntered: boolean;
  /**
   * When true and any visible rate resolves to `0` (free), the picker hides
   * every paid option so the shopper is automatically given the free rate.
   */
  hideRatesWhenFreeAvailable: boolean;
}

/**
 * Account-creation policy. Subsumes the legacy `FeatureFlags.guestCheckout`
 * toggle on `ScriptSettings` — when `accounts.allowGuestCheckout` is set, it
 * takes precedence; otherwise the legacy flag is read as a fallback for
 * pre-v2.10 stores. Added in v2.10.
 */
export interface AccountSettings {
  /**
   * When true, shoppers can complete checkout without a full email+password
   * account — the storefront signs them in with Firebase anonymous auth so
   * Firestore rules still pass. Requires Anonymous sign-in to be enabled in
   * Firebase Authentication.
   */
  allowGuestCheckout: boolean;
  /** When true, the checkout shows a "Create an account" option for shoppers who aren't signed in. */
  allowAccountCreationAtCheckout: boolean;
  /** When true, the My Account / register page accepts new sign-ups. When false, the page renders a "registration disabled" notice. */
  allowAccountCreationOnMyAccount: boolean;
  /**
   * When true, new registrations skip the "pick a password" step — the
   * storefront generates a random password, signs the user in, and emails
   * them a password-reset link so they can pick a real password on their
   * own terms. Useful for purchase-flow sign-ups.
   */
  sendPasswordSetupLink: boolean;
}

/**
 * GDPR-style personal-data retention. Every field is optional — `undefined`
 * means "keep indefinitely". A scheduled Cloud Function in `functions-admin`
 * reads these values daily and deletes eligible docs from Firestore (and
 * matching auth users). Added in v2.10.
 */
export interface PrivacyRetentionSettings {
  /** Delete user docs (and their Auth record) with no activity for this many days. */
  retainInactiveAccountsDays?: number;
  /** Delete orders in status `'cancelled'` older than this many days. */
  retainCancelledOrdersDays?: number;
  /** Delete orders in a failed / errored state older than this many days. */
  retainFailedOrdersDays?: number;
  /** Delete orders in status `'delivered'` older than this many days. */
  retainCompletedOrdersDays?: number;
  /** Delete error log docs older than this many days. Added for mod1182. */
  retainErrorLogsDays?: number;
}

/**
 * Closed set of transactional email templates the library ships. Each key
 * corresponds to a Firestore doc at `emailTemplates/{key}` that the admin
 * can edit independently. Added in v2.11.
 *
 * Admin emails (→ merchant): `new_order_admin`, `cancelled_order_admin`,
 * `failed_order_admin`. Customer emails (→ shopper):
 * `processing_order`, `completed_order`, `refunded_order`, `customer_note`,
 * `new_account`.
 *
 * Note: password-reset emails are handled natively by Firebase Auth and are
 * not templated here — change the look in the Firebase console instead.
 */
export type EmailTemplateKey =
  | 'new_order_admin'
  | 'cancelled_order_admin'
  | 'failed_order_admin'
  | 'processing_order'
  | 'completed_order'
  | 'refunded_order'
  | 'customer_note'
  | 'new_account'
  | 'new_contact_admin'
  | 'contact_autoreply';

export const EMAIL_TEMPLATE_KEYS: readonly EmailTemplateKey[] = [
  'new_order_admin',
  'cancelled_order_admin',
  'failed_order_admin',
  'processing_order',
  'completed_order',
  'refunded_order',
  'customer_note',
  'new_account',
  'new_contact_admin',
  'contact_autoreply',
] as const;

/** Whether a template's primary recipient is the merchant (`admin`) or the shopper (`customer`). */
export type EmailAudience = 'admin' | 'customer';

/**
 * A single editable email template. `key` is the stable identifier the Cloud
 * Function keys off of; `subject`, `heading`, `additionalContent` are the
 * only merchant-authored strings — the surrounding HTML shell is rendered
 * by the sender from the global `EmailSettings`. Added in v2.11.
 */
export interface EmailTemplate {
  id: EmailTemplateKey;
  key: EmailTemplateKey;
  /** `false` suppresses sending for this template entirely. */
  enabled: boolean;
  /** Email subject line. Supports `{placeholder}` substitution. */
  subject: string;
  /** Large heading at the top of the email body. Supports `{placeholder}` substitution. */
  heading: string;
  /**
   * Optional merchant copy shown below the heading, above the order summary.
   * Supports `{placeholder}` substitution and newlines. Stored as plain text;
   * rendered into paragraphs by the sender.
   */
  additionalContent: string;
  /**
   * Admin recipients for `audience: 'admin'` templates. Empty array → fall
   * back to `SiteSettings.contactEmail`. Ignored for customer templates.
   */
  recipients: string[];
  /** Used for grouping / routing in admin and the sender. Not merchant-editable. */
  audience: EmailAudience;
  updatedAt: Timestamp;
}

/**
 * Merchant-authored global sender config for transactional emails. Lives at
 * `emailSettings/site` and is loaded by both the admin UI (for editing) and
 * the Cloud Function (for rendering). Added in v2.11.
 */
export interface EmailSettings {
  id: 'site';
  /** Sender display name (e.g. "Acme Store"). Falls back to `SiteSettings.brandName`. */
  fromName: string;
  /** Sender email address. Must be verified with the underlying provider (SendGrid, SES, etc.). */
  fromAddress: string;
  /** Optional Reply-To header. Leave blank to use the From address. */
  replyTo?: string;
  /** Logo URL shown at the top of every email body. Falls back to `SiteSettings.logoUrl`. */
  logoUrl?: string;
  /** Color palette applied to the email shell (header background, button background, body text). */
  accentColor: string;
  backgroundColor: string;
  /** Footer copy shown below every email (company address, unsubscribe note). Plain text; newlines split paragraphs. */
  footerText: string;
  /**
   * Master toggle. When `false`, the Cloud Function logs and exits without
   * sending any email. Useful during development to avoid accidental sends.
   */
  enabled: boolean;
  updatedAt: Timestamp;
}

export interface SiteSettings {
  logoUrl: string;
  faviconUrl?: string;
  brandName: string;
  brandDescription: string;
  contactEmail: string;
  contactPhone: string;
  contactAddress: string;
  businessHours: string;
  /**
   * Structured weekly business hours. When set + `enabled`, the storefront
   * renders this (on `/contact`) instead of the legacy free-text
   * `businessHours`. Edited on the admin Settings → Contact section. Added
   * in v9.17.
   */
  businessHoursSchedule?: BusinessHoursSchedule;
  /** ISO 4217 currency code (e.g. `USD`, `EUR`). Optional — added in v1.19. */
  currency?: string;
  /** IANA timezone (e.g. `America/New_York`). Optional — added in v1.19. */
  timezone?: string;
  /** ISO 3166-1 alpha-2 country code (e.g. `US`, `GB`). Optional — added in v1.19. */
  country?: string;
  /**
   * Tax calculation mode. When `undefined` or `'none'`, no tax row renders on
   * the checkout. When `'flat'`, `flatTaxRate` applies site-wide. When
   * `'per-country'`, the rate is read from the selected country's entry in
   * `supportedCountries`. Added in v2.5.
   */
  taxMode?: TaxMode;
  /** Display label for the tax row (e.g. `Sales tax`, `VAT`). Defaults to "Tax". Added in v2.5. */
  taxLabel?: string;
  /** Decimal tax rate 0–1 used under `taxMode: 'flat'`. Ignored otherwise. Added in v2.5. */
  flatTaxRate?: number;
  /**
   * Countries the store sells to. When populated, the checkout country
   * dropdown is restricted to this list. When empty or undefined, the library
   * falls back to the global ISO 3166 list. Added in v2.5.
   */
  supportedCountries?: SupportedCountry[];
  /** Tax display + calculation preferences. Additive; defaults preserve pre-v2.12 behavior. Added in v2.12. */
  taxConfig?: TaxConfig;
  /** Maintenance / pre-launch splash. Added in v2.7. */
  comingSoon?: ComingSoonSettings;
  /** Price formatting overrides. Added in v2.7. */
  currencyDisplay?: CurrencyDisplay;
  /**
   * Structured physical store address. When set, overrides `contactAddress`
   * everywhere it's rendered. Added in v2.7.
   */
  storeAddress?: StoreAddress;
  /** Review submission policy. Added in v2.7. */
  reviewPolicy?: ReviewPolicy;
  /** Add-to-cart behavior. Added in v2.7. */
  cartBehavior?: CartBehavior;
  /** Inventory tracking + display config. Added in v2.9. */
  inventory?: InventorySettings;
  /** Checkout shipping rate display rules. Added in v2.9. */
  shippingOptions?: ShippingOptions;
  /** Account-creation policy (guest checkout, registration gating). Added in v2.10. */
  accounts?: AccountSettings;
  /** Personal-data retention policy read by the scheduled cleanup Cloud Function. Added in v2.10. */
  privacy?: PrivacyRetentionSettings;
  /**
   * Ids of enabled product taxonomies (from `COMMON_TAXONOMIES` in
   * `src/taxonomies`). Only enabled taxonomies show in the /admin/taxonomies
   * sidebar. When `undefined`, the store falls back to the catalog defaults
   * (Brands only). Edited on Settings → Taxonomies and in the setup wizard.
   * Added in v9.13.0.
   */
  enabledTaxonomies?: string[];
  socialLinks: SocialLink[];
}

export interface SearchTerm {
  id: string;
  term: string;
  count: number;
  firstSearchedAt?: Timestamp;
  lastSearchedAt?: Timestamp;
}

export interface PromoCode {
  id: string;
  code: string;
  type: 'percentage' | 'fixed';
  value: number;
  minOrderAmount?: number;
  maxDiscount?: number;
  isActive: boolean;
  createdAt: Timestamp;
}

/** Client-side shape after a promo code has been validated against a subtotal. */
export interface AppliedPromoCode {
  code: string;
  type: 'percentage' | 'fixed';
  value: number;
  discountAmount: number;
}

export interface ShippingPluginInstall {
  id: string;
  /** Which built-in plugin handles this install (flat-rate, free-shipping, etc.). */
  pluginId: ShippingPluginId;
  /** Merchant-authored display label shown to shoppers (e.g. "Standard", "Weekend Express"). */
  name: string;
  /** When false, the install is hidden from checkout and the public shipping page. */
  enabled: boolean;
  order: number;
  estimatedDays: { min: number; max: number };
  /** Plugin-specific configuration. Validated by the plugin's `validateConfig` at runtime. */
  config: Record<string, unknown>;
  /**
   * ISO 3166-1 alpha-2 codes of countries this shipping method is available
   * in. Empty or undefined → all `SiteSettings.supportedCountries`. Added in v2.5.
   */
  eligibleCountries?: string[];
  createdAt: Timestamp;
}

export interface PaymentPluginInstall {
  id: string;
  /** Which built-in plugin handles this install (currently: 'stripe'). */
  pluginId: string;
  /** Merchant-authored display label shown in admin (e.g. "Stripe — Production"). */
  name: string;
  /**
   * Optional merchant-authored blurb shown to shoppers at checkout under the
   * gateway name (e.g. "Pay securely with Stripe"). When absent, checkout
   * falls back to the plugin's catalog description. Added in v2.8.
   */
  description?: string;
  /** When false, `useCheckout` skips this install. */
  enabled: boolean;
  order: number;
  /** Plugin-specific configuration. Validated by the plugin's `validateConfig` at runtime. */
  config: Record<string, unknown>;
  createdAt: Timestamp;
}

/**
 * Persisted install of an email-provider plugin. Added in v2.14 to replace
 * the v2.11 `SENDGRID_API_KEY` Functions secret. Admin-only read/write —
 * the API key lives in `config`, so the collection must not be publicly
 * readable like shipping/payment installs are.
 */
export interface EmailPluginInstall {
  id: string;
  /** Which built-in plugin handles this install: 'sendgrid' or 'brevo'. */
  pluginId: string;
  /** Merchant-authored display label shown in admin (e.g. "SendGrid — production"). */
  name: string;
  /** When false, the dispatcher skips this install. Only the first enabled install is used. */
  enabled: boolean;
  order: number;
  /** Plugin-specific configuration (includes apiKey). Validated by the plugin's `validateConfig` at runtime. */
  config: Record<string, unknown>;
  createdAt: Timestamp;
}

/**
 * Source of an error log entry. `client` covers React render errors, global
 * window handlers; `service` is an admin-page or context service call that
 * failed at the call site; `cloud-function` is a failure captured in one of
 * the Firebase Functions codebases via `reportFunctionError`.
 */
export type ErrorLogSource = 'client' | 'service' | 'cloud-function';

/**
 * One captured error on this installation. Added for mod1182 self-healing
 * error logging. Surfaced on the admin About page; trimmed by the daily
 * retention sweep when `PrivacyRetentionSettings.retainErrorLogsDays` is set.
 *
 * Writes are validated by `match /errorLogs/{id}` in firestore.rules —
 * keep the shape and length caps in sync with those checks.
 */
export interface ErrorLog {
  id: string;
  timestamp: Timestamp;
  source: ErrorLogSource;
  /** Stable identifier for where the error came from (e.g. `ErrorBoundary`, `auth-context.fetchProfile`, `caspian-stripe.createCheckout`). */
  origin: string;
  /** Redacted error message. */
  message: string;
  /** Redacted + truncated stack (≤ 4000 chars). */
  stack?: string;
  /** Small scalar-only bag for extra context (request id, plugin id, …). */
  context?: Record<string, string | number | boolean>;
  userAgent?: string;
  /** `location.pathname` at the time of the client-side error. */
  route?: string;
  /** `CASPIAN_STORE_VERSION` at the time of the error. */
  libraryVersion: string;
  firebaseProjectId?: string;
  /** Bumps when the same (origin, message) recurs within 24h. Admin-only update. */
  seenCount: number;
  lastSeenAt: Timestamp;
}

export interface ProductCategoryDoc {
  id: string;
  name: string;
  slug: string;
  description?: string;
  order: number;
  isActive: boolean;
  isFeatured?: boolean;
  imageUrl?: string;
  parentId?: string | null;
  path?: string[];
  depth?: number;
  createdAt: Timestamp;
}

export interface ProductBrandDoc {
  id: string;
  name: string;
  isActive: boolean;
  createdAt: Timestamp;
}

/**
 * A term under a generic product taxonomy (materials, seasons, colors, …).
 * One `taxonomyTerms` collection holds every generic taxonomy's terms, keyed
 * by `type` (a taxonomy id from `COMMON_TAXONOMIES` in `src/taxonomies`).
 * Brands stay in their own `productBrands` collection. Doc id is
 * `${type}__${slug}` so the same term name can exist under different
 * taxonomies. Added in v9.13.0.
 */
export interface TaxonomyTermDoc {
  id: string;
  /** Taxonomy id this term belongs to (e.g. `materials`). Immutable after create. */
  type: string;
  name: string;
  slug: string;
  isActive: boolean;
  order?: number;
  createdAt: Timestamp;
}

export interface ProductCollectionDoc {
  id: string;
  name: string;
  slug: string;
  description?: string;
  imageUrl?: string;
  productIds: string[];
  isActive: boolean;
  isFeatured?: boolean;
  order: number;
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

export interface PageContent {
  id: string;
  pageKey: string;
  title: string;
  subtitle?: string;
  content: string;
  updatedAt: Timestamp;
}

export interface LanguageDoc {
  id: string;
  code: string;
  name: string;
  nativeName: string;
  flag?: string;
  isDefault: boolean;
  isActive: boolean;
  direction: 'ltr' | 'rtl';
  order: number;
  updatedAt?: Timestamp;
}

/**
 * A single item in the admin setup / operational todo list. Used by
 * `<AdminTodoPage>` to track first-run actions ("deploy rules", "configure
 * Stripe", etc.) and any follow-up tasks the admin adds. `isDefault` marks
 * the seeded first-run tasks so they render distinctly.
 */
export interface AdminTodo {
  id: string;
  title: string;
  description?: string;
  done: boolean;
  order: number;
  isDefault: boolean;
  createdAt: Timestamp;
  updatedAt?: Timestamp;
}

// --- Script-level site configuration (new) ---

export interface ThemeTokens {
  primary: string;
  primaryForeground: string;
  accent: string;
  radius: string;
  fontFamily?: string;
  /**
   * Optional page background color, written to `--caspian-background` by
   * `<ThemeInjector>`. When omitted, falls back to `#ffffff` from globals.css.
   * Added in v8.1 so themes can paint the page beneath the storefront — the
   * default Clean theme uses pure white; dark themes can specify their own.
   */
  background?: string;
}

export interface FontTokens {
  body: string;
  headline: string;
  /** Optional Google Fonts family list (e.g. `Montserrat:wght@400;700`). When set the provider injects the <link> tag. */
  googleFamilies?: string[];
}

export interface HeroTokens {
  title: string;
  subtitle: string;
  cta: string;
  /** Optional call-to-action destination (default: /products). */
  ctaHref?: string;
  imageUrl?: string;
}

/** Rows of a single size table rendered by `<SizeGuidePage>`. */
export interface SizeTableRow {
  /** Free-form label for the left-most column (e.g. 'XS', 'S', '6', 'EU 39'). */
  label: string;
  /** The remaining columns keyed by header. */
  [column: string]: string;
}

export interface SizeTable {
  /** Heading shown above the table. */
  title: string;
  /** Column headers in display order. The first entry is the label column. */
  columns: string[];
  rows: SizeTableRow[];
}

export interface SizeGuideConfig {
  tips?: string;
  tables: SizeTable[];
}

export interface FeatureFlags {
  reviews: boolean;
  questions: boolean;
  wishlist: boolean;
  promoCodes: boolean;
  /**
   * @deprecated Superseded by `SiteSettings.accounts.allowGuestCheckout` in v2.10.
   * Kept for backward compat — read as a fallback when `accounts` is absent.
   */
  guestCheckout: boolean;
  multiLanguage: boolean;
}

/** Per-card UI display toggles for `<ProductCard />`. Added in v8.18.0. */
export interface ProductCardSettings {
  /** Render a heart icon on the top-right of the card image to toggle wishlist. */
  showWishlistIcon: boolean;
  /** Render a cart icon at the bottom-right of the card to quick-add to cart. */
  showQuickAddIcon: boolean;
}

export interface ScriptSettings {
  id: 'site';
  brandName: string;
  brandDescription: string;
  defaultCurrency: string;
  defaultLocale: string;
  supportedLocales: string[];
  theme: ThemeTokens;
  /** Optional — added in v1.1 for later phases. Consumers can ignore. */
  fonts?: FontTokens;
  /** Optional — added in v1.1 for later phases. Consumers can ignore. */
  hero?: HeroTokens;
  /** Optional — added in v1.4. Drives the `<SizeGuidePage />`. */
  sizeGuide?: SizeGuideConfig;
  features: FeatureFlags;
  /** Optional — added in v8.18.0. Drives icon visibility on `<ProductCard />`. */
  productCard?: ProductCardSettings;
  /**
   * Id of the storefront template currently active (v9.0.0-alpha.1+).
   * Empty string (or absent) means the default storefront components
   * render — backward compatible with all pre-v9 installs. Set by
   * `applyTemplate()` and read by `<TemplateProvider>` to resolve
   * `useTemplateComponent()` lookups.
   */
  activeTemplateId?: string;
  updatedAt: Timestamp;
}

export const DEFAULT_SCRIPT_SETTINGS: Omit<ScriptSettings, 'updatedAt'> = {
  id: 'site',
  brandName: 'My Store',
  brandDescription: 'Powered by Caspian Store',
  defaultCurrency: 'USD',
  defaultLocale: 'en',
  supportedLocales: ['en'],
  theme: {
    primary: '#1a73e8',
    primaryForeground: '#ffffff',
    accent: '#1a73e8',
    radius: '1rem',
    background: '#ffffff',
    fontFamily: "'Poppins', system-ui, -apple-system, sans-serif",
  },
  fonts: {
    body: "'Poppins', system-ui, -apple-system, sans-serif",
    headline: "'Poppins', system-ui, -apple-system, sans-serif",
    googleFamilies: ['Poppins:wght@300;400;500;600;700'],
  },
  hero: {
    title: 'Shop our latest collection',
    subtitle: 'Curated essentials delivered to your door.',
    cta: 'Shop now',
    ctaHref: '/products',
  },
  features: {
    reviews: true,
    questions: true,
    wishlist: true,
    promoCodes: true,
    guestCheckout: true,
    multiLanguage: false,
  },
  productCard: {
    showWishlistIcon: true,
    showQuickAddIcon: true,
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// Page builder (ported from luivante v9.3→v9.5). Self-contained; depends only on
// Timestamp + these types. See src/page-builder/.
// ─────────────────────────────────────────────────────────────────────────────

/** A responsive breakpoint the builder can target. */
export type Breakpoint = 'desktop' | 'tablet' | 'mobile';

/**
 * Per-edge spacing. Edge values are unit-less numbers; the box-level `unit`
 * (absent ⇒ `'px'`, for back-compat with layouts saved before units existed)
 * applies to all four edges. Any edge omitted = inherit / 0.
 */
export interface BoxSpacing {
  top?: number;
  right?: number;
  bottom?: number;
  left?: number;
  /** Length unit for all four edges. Absent = `'px'`. */
  unit?: 'px' | 'rem' | '%' | 'vw';
}

/**
 * Credit for an image inserted from the stock-image search. Captured so the
 * storefront can render attribution — a legal requirement for CC-BY* images
 * (CC0 / public-domain make it optional). `attributionText` is the provider's
 * ready-to-render string.
 */
export interface StockImageAttribution {
  source: 'openverse';
  title: string;
  creator: string | null;
  creatorUrl: string | null;
  license: string;
  licenseVersion: string;
  licenseUrl: string;
  foreignLandingUrl: string;
  attributionText: string;
}

/** One normalized stock-image search result (from the stock-image proxy). */
export interface StockImageResult {
  id: string;
  thumbUrl: string;
  fullUrl: string;
  title: string;
  width: number;
  height: number;
  attribution: StockImageAttribution;
}

/**
 * Per-block visual overrides the renderer applies as inline styles on the block
 * wrapper. Empty/omitted = the design-system default for the block's type.
 */
export interface BlockStyle {
  background?: {
    color?: string;
    imageUrl?: string;
    /** `cover` | `contain` | `auto` | a CSS background-size. */
    size?: string;
    /** CSS background-position, e.g. `center` or `30% 70%` (focal point). */
    position?: string;
    /** When true, tile the image instead of `no-repeat`. */
    repeat?: boolean;
    /** Optional rgba() laid over the image (darken/tint). */
    overlay?: string;
    /** A CSS gradient used AS the background when no image is set. */
    gradient?: string;
    /** A CSS gradient laid OVER the image (replaces the flat `overlay` when set). */
    overlayGradient?: string;
    /** Credit for a stock image used as the background. */
    imageAttribution?: StockImageAttribution;
  };
  padding?: BoxSpacing;
  margin?: BoxSpacing;
  align?: 'left' | 'center' | 'right';
  /** CSS width for the block (columns: track width; widgets: max-width). */
  width?: string;
  textColor?: string;
  /** Typography overrides. All optional; absent = inherit. */
  typography?: {
    fontSize?: string;
    fontWeight?: number;
    lineHeight?: string;
    letterSpacing?: string;
    textTransform?: 'none' | 'uppercase' | 'lowercase' | 'capitalize';
  };
  border?: { width?: number; style?: 'solid' | 'dashed' | 'dotted'; color?: string };
  /** Corner radius: a single px value, or per-corner px values. */
  radius?: number | { topLeft?: number; topRight?: number; bottomRight?: number; bottomLeft?: number };
  /** Box-shadow: a preset token (`sm|md|lg|xl`) or a custom CSS box-shadow. */
  shadow?: string;
}

/**
 * One block placed on an editable page. `type` keys into the block catalog
 * (`src/page-builder/catalog.ts`). `props` holds editable field values, merged
 * over the catalog entry's `defaultProps` at render. `children` holds nested
 * blocks for container/column types.
 */
export interface PageBlock {
  id: string;
  type: string;
  visible: boolean;
  variant?: string;
  props: Record<string, unknown>;
  style?: BlockStyle;
  responsive?: Partial<
    Record<Breakpoint, { style?: BlockStyle; props?: Record<string, unknown>; hidden?: boolean }>
  >;
  children?: PageBlock[];
}

/** Legacy flat section list (pre block-tree). Migrated to blocks on read. */
export type SectionInstance = Pick<PageBlock, 'id' | 'type' | 'visible' | 'variant' | 'props'>;

/**
 * A page's PUBLISHED layout (`pageLayouts/{id}`). Absent doc → the storefront
 * renders the catalog's seed defaults. `version` is the monotonic publish
 * counter (draft/publish concurrency + revision id).
 */
export interface PageLayout {
  id: string;
  schemaVersion?: number;
  blocks: PageBlock[];
  updatedAt: Timestamp;
  version?: number;
  publishedAt?: Timestamp;
}

/**
 * A page's working DRAFT (`pageLayoutDrafts/{id}`) — admin-only; never read by
 * the storefront. `baseVersion` is the published version it forked from;
 * `draftRev` bumps each save (optimistic concurrency).
 */
export interface DraftLayout {
  id: string;
  schemaVersion?: number;
  blocks: PageBlock[];
  updatedAt: Timestamp;
  baseVersion: number;
  draftRev: number;
  updatedBy?: string;
  updatedByName?: string;
}

/** Metadata for one published-layout revision (`pageLayouts/{id}/revisions/{version}`). */
export interface PageRevisionMeta {
  version: number;
  createdAt: Timestamp;
  createdByName?: string;
  source: 'publish' | 'restore';
}

/**
 * A page-builder–managed page beyond the homepage. The doc id is the URL slug;
 * its block layout lives in `pageLayouts/{slug}`. `status` gates public
 * rendering — drafts render only for admins.
 */
export interface BuilderPage {
  id: string;
  slug: string;
  title: string;
  status: 'draft' | 'published';
  updatedAt: Timestamp;
}
